server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  security:
    user:
      name: text@naver.com
      password: 1q2w3e4r!

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.clj74ayzyl6j.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220930
    username: admin
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml


file:
  path: C:/daeun/stussy-clone-20220930-daeun-main/src/main/resources/static/upload/