server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  security:
    user:
      name: text@naver.com
      password: 1q2w3e4r!
    oauth2:
      client:
        registration:
          google:
            clientId: 666333067567-3hsmbf0vmlo8ccmr9dne7tgv3vhegu3v.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            clientId: 6AkIP0Q5zdFmwqwKBC0F
            clientSecret: vD7FiRYkik
            scope:
              - email
              - name
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUrl: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response



  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.clj74ayzyl6j.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220930
    username: admin
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml


